memo: ||md
  ### この後の作業メモ(4/15) 
  - 要件から設計の前
    - 詳細化（ユースケース）
    - 見積もりを出すために必要な情報
  - 推奨体制・人材（新人の場所）
  - 機能種別と序列
  - 品質・デリバリーのチェックポイント(QCDのQD)
||

requirement: {
  label: "要求/要件定義"
  development {
    label: "要求開発"
  }
  management {
    label: "要求管理"
  }
  definition: {
    direction: right
    label: "要件定義"
    functional {
      label: "機能要件"
    }
    non-functional {
      label: "非機能要件"
    }
    prioritization {
      label: "優先順位の決定"
    }
    validation {
      label: "検証"
    }
  }
}
requirement.definition -> specification.backlog: "ユーザーストーリーの構築"
specification: {
  label: "仕様定義"

  backlog: "プロダクトバックログ" {
    direction: down
    epic: "エピック"
    story: {
      label: "ストーリー"
    }
    feature: "フィーチャー"
    epic -> story
    story -> feature
  }
  domain-model: {
    label: "ドメインモデル"
    class: ai-effective-weak
  }
  integration-test-design: {
    label: "結合テスト設計"
    class: ai-effective-weak
  }
  backlog -> integration-test-design
  backlog -> domain-model
}
