classes: {
  command: {
    style: {
      fill: "#ffff88"
    }
  }
  ai-effective-weak: {
    style: {
      fill: "#ffcccc"
    }
  }
  ai-effective: {
    style: {
      fill: "#ff8888"
    }
  }
  ai-effective-strong: {
    style: {
      fill: "#cc4444"
      stroke: "#990000"
      stroke-width: 2
    }
  }
  cost-cut: {
    label: "コストへの影響"
    style: {
      stroke: "#990000"
      stroke-width: 4
    }
  }
  person: {
    shape: person
    style: {
      stroke: "blue"
      fill: "#aaffff"
    }
  }
  ai: {
    shape: person
    style: {
      stroke: "#6a1b9a"
      fill: "#f3e5f5"
    }
  }
  ai-field: {
    label: ""
    style: {
      stroke-width: 0
      fill: "#ffffff"
    }
  }
  field: {
    label: ""
    style: {
      stroke-width: 0
      fill: "#ffffff"
    }
  }

  spec: {
    style: {
      fill: "#fef3c7"
      stroke: "#d97706"
      stroke-width: 2
    }
  }
  agent: {
    style: {
      fill: "#e0e7ff"
      stroke: "#4f46e5"
      stroke-width: 2
    }
  }
  output: {
    style: {
      fill: "#f0fdf4"
      stroke: "#16a34a"
      stroke-width: 2
    }
  }
  human: {
    style: {
      fill: "#f1f5f9"
      stroke: "#475569"
    }
  }
}

grid-rows: 2

agents: spec駆動開発 {
  direction: right
  cost-cut: {
    class: cost-cut
    description: ||md
      # spec駆動開発の効果の計算(凡例)
      - 効果のレベルを5種類に区別する
        - **省略** : AIエージェントの導入により、省略される工程( **工数削減: 100%** )
        - **AI(要レビュー)** : AIエージェントの導入により、レビューのみとなる工程( **工数削減: 90%**)
        - **AI(対話)** : AIエージェントの導入により、エンジニアの手作業をほぼ肩代わりできるもの( **工数削減: 80%** )
        - **AI(一部手作業)** : AIエージェントの導入により、手作業はなくならないが工数を削減できるもの( **工数削減: 50%** )
        - (記載せず) : AIエージェント・AIアシスタントを導入してもエンジニアの工数が削減できないもの( **工数削減: 0%** )
      ||

  }

  # 人間系
  UserZone: 人間系 {
    style: {
      stroke-dash: 5
    }
    U: プロダクトオーナー\nエンジニアなど {
      shape: person
      class: human
    }
  }

  # 核となる仕様
  spec: "核: 実行可能な仕様書\n(Spec as Single Source of Truth)" {
    shape: cylinder
    class: spec
  }

  # AI オーケストレーター
  ai-orchestrator: AI オーケストレーター {
    style: {
      fill: "#f8fafc"
    }
    planner: プランニングAI { class: agent }
    Coder: {
      Schemer: データモデルデザインAI { class: agent }
      Frontend: フロントエンド実装AI { class: agent }
      Backend: バックエンド実装AI { class: agent }
    }
    Tester: テスト実装・実行AI { class: agent }
    Refiner: リファクタリングAI { class: agent }

    planner -> Coder: タスク分解
    planner -> Tester: テストシナリオ作成
    Coder -> Tester: 生成コード
    Tester -> planner: フィードバック/エラー
    Tester -> Refiner: 合格
    Refiner -> Coder: 最適化
  }

  # アウトプット (CI/CD)
  cd-ci: アウトプット {
    Prod: プロダクトコード { class: output }
    Doc: 技術ドキュメント\nテスト結果 { class: output }
  }

  # インタラクション（接続関係）
  UserZone.U -> spec: 仕様定義/プロンプト
  spec <-> ai-orchestrator.planner: コンテキスト参照/更新

  ai-orchestrator.Refiner -> cd-ci.Prod: 最終コード
  ai-orchestrator.Tester -> cd-ci.Doc: レポート

  cd-ci.Prod -> UserZone: デプロイ {
    style: { stroke-dash: 3 }
  }
  cd-ci.Doc -> UserZone: レビュー {
    style: { stroke-dash: 3 }
  }
}

dev: {
  class: field
  grid-columns: 6
  grid-gap: 0

  requirement: {
    direction: right
    label: "要求/要件定義"
    development {
      label: "要求開発"
    }
    management {
      label: "要求管理"
    }
    definition: {
      direction: right
      label: "要件定義"
      functional {
        label: "機能要件"
      }
      non-functional {
        label: "非機能要件"
      }
      prioritization {
        label: "優先順位の決定"
      }
      validation {
        label: "検証"
      }
    }
  }
  requirement.definition -> specification.backlog: "ユーザーストーリーの構築"
  requirement.definition -> specification.domain-model: "ドメイン分析"
  specification: {
    direction: right
    label: "仕様定義"
    description: ||md
      - エピック、またはストーリーのレベルまでは人間の手で作成する必要がある
      - AIによる開発速度の向上により、一部の「エピック」は1イテレーションで実装できる「ストーリー」となる
      - AIのためのタスクに分割し、エージェントに割り当てるのは **AI planner** の作業となる
    ||

    backlog: "プロダクトバックログ" {
      direction: down
      epic: "エピック"
      story: {
        label: "ストーリー"
      }
      feature: "フィーチャー"
    }
    domain-model: "ドメインモデル"
  }

  specification.domain-model -> design.model: 具体化
  specification.backlog -> design.task: タスク分割

  design: {
    direction: right
    label: "設計"
    cost-cut: {
      class: cost-cut
      label: 設計全体のコストへの影響
      description: ||md
        # 定量的に削減できる工数
        | 項目 | 割合 | 工数への影響 |
        |-|-|-|
        | 環境構築 | 5% | 70% |
        | タスク | 5% | 100% |
        | フロントエンド | 40% | 50% |
        | データモデル | 10% | 80% |
        | バックエンド - サービス | 20% | 86% |
        | バックエンド - データベース | 10% | 90% |
        | バックエンド - インフラ | 10% | 80% |
        | **割合×工数への影響の合計** | 100% | **70.7%減** |
      ||
    }

    task: {
      label: "タスク"
      class: ai-effective
      cost-cut: {
        class: cost-cut
        description: ||md
          ## 対象となる作業
          - エピック、ストーリー、フィーチャーを個別のタスクにする
            - 従来 : 担当エンジニアへの割り当て
              - タスクをチケット化する
            - 変化 : AIエージェントに向けたタスクとして切り出す
              - リポジトリ上に一時的に出力して、タスクを終えたら削除する
              - 永続的な文書はチケットに残す
          ## 定量的に削減できる工数
          | 項目 | 工数割合 | 削減効果 |
          |-|-|-|
          | 省略 | 100% | 100% |
          | **割合×工数への影響の合計** | 100% | **100%減** |
        ||
      }
    } 
    task -> frontend
    task -> backend
    task -> develop-env

    frontend {
      label: "フロントエンド"
      class: ai-effective-weak
      cost-cut: {
        class: cost-cut
        description: ||md
          ## AI導入による変化
          | | AsIs | ToBe | 割合 |
          |-|-|-|-|
          | 情報アーキテクチャ | 手作業 | AI(一部手作業) | 20% |
          | UX(コンポーネント、ナビゲーション) | 手作業 | AI(一部手作業) | 40% |
          | 状態管理・セッション管理 | 手作業 | AI(一部手作業) | 20% |
          | スタイルガイド | 手作業 | AI(一部手作業) | 20% |
          ## 定量的に削減できる工数
          | 項目 | 割合 | 工数への影響 |
          |-|-|-|
          | AI(一部手作業) | 100% | 50%減 |
          | **割合×工数への影響の合計** | 100% | **50%減** |
        ||
      }
    }

    develop-env {
      label: "環境構築"
      class: ai-effective-weak
      cost-cut: {
        class:cost-cut
        description: ||md
          ## 作業内容
          - 動作環境・フレームワーク設計
          - 開発環境と運用官僚の両面から各種環境を決定する
          ## AI導入による変化
          | | AsIs | ToBe | 割合 |
          |-|-|-|-|
          | 環境設計 | 手作業 | AI(要レビュー) | 50% |
          | 開発環境導入 | 手作業 | AI(一部手作業) | 50% |
          ## 定量的に削減できる工数
          | 項目 | 割合 | 工数への影響 |
          |-|-|-|
          | AI(要レビュー) | 50% | 90%減 |
          | AI(一部手作業) | 50% | 50%減 |
          | **割合×工数への影響の合計** | - | **70%減** |
        ||
      }
    }

    model: {
      label: "データモデル"
      class: ai-effective-weak
      cost-cut: {
        class:cost-cut
        description: ||md
          ## 作業項目
          - エンジニアが決めるべきところ、実施すべきこと
            - 要求に対して必ず守るべきこと
            - 各種規則(命名規約など)
            - データ構造に関して人間が決めるべき部分
            - 外部サービスやAPIのキーの取得と環境変数への記述
          - AIの仕事
            - AIエージェントと技術者向けの文書を .md で残す
              - 物理削除、論理削除、履歴管理などについて明記する
              - 認証認可に関して記述する
          ## AI導入による変化
          | | 現在 | 導入後 | 割合 |
          |-|-|-|-|
          | 閲覧者 | エンジニア | AIとエンジニア | - |
          | メンテナンス | 放置されがち | 根幹の指示書であるため常に最新維持 | - |
          | 更新時 | 手作業 | 手作業またはAIのアシストを受けて更新、実装の更新をAIに指示する | - |
          | 設計作業 | 手作業 | AI(対話) | 100% |
          ## 定量的に削減できる工数
          | 項目 | 割合 | 工数への影響 |
          |-|-|-|
          | AI(対話) | 100% | 80%減 |
          | **割合×工数への影響の合計** | - | **80%減** |
        ||
      }
    }

    backend {
      label: "バックエンド"

      endpoint {
        label: "サービス"
        class: ai-effective-weak

        cost-cut: {
          class: cost-cut
          description: ||md
            ## 作業項目
            - DTOとCRUD系APIはAIがデータモデルに即して直接実装するため設計不要となる
              - 実装時のレビューコストは残るが、設計はデータモデルの記述が終わった時点で完了している
            - API側の複雑なビジネスロジック、サービスは従来通りのデザインをAI支援下で行う
            - API側の決め事であるロギング、ヘルスチェックは従来通りのデザインをAI支援下で行う
            - API呼び出し側のエラー処理、リトライ処理、モニタリング処理は従来通りのデザインをAI支援下で行う
            ## AI導入による変化
            | | AsIs | ToBe | 割合 |
            |-|-|-|-|
            | **DTO設計 / CRUD設計** | 手作業 | 省略 | 25% |
            | ビジネスロジック設計 | 手作業 | AI(対話) | 35% |
            | サービス設計 | 手作業 | AI(対話) | 30% |
            | ロギング仕様、ヘルスチェック仕様 | 手作業 | AI(要レビュー) | 5% |
            | 呼び出し側のエラー処理、リトライ処理、モニタリング処理 | 手作業 | AI(要レビュー) | 5% |
            | リファレンス出力 | Swagger | Swagger | - |
            ## 定量的に削減できる工数
            | 項目 | 割合 | 工数への影響 |
            |-|-|-|
            | 省略 | 25% | 100%減 |
            | AI(要レビュー) | 10% | 90%減 |
            | AI(対話) | 65% | 80%減 |
            | **割合×工数への影響の合計** | - | **86%減** |
          ||
        }
      }
      db {
        label: "データベース"
        class: ai-effective

        cost-cut: {
          class: cost-cut
          description: ||md
            ## AI導入による変化
            | | AsIs | ToBe | 割合 |
            |-|-|-|-|
            | テーブル | 手作業 | AI(要レビュー) | 40% |
            | リレーション | 手作業 | AI(要レビュー) | 40% |
            | インデックス | 手作業 | AI(要レビュー) | 10% |
            | カスケード | 手作業 | AI(要レビュー) | 10% |

            ## 定量的に削減できる工数
            | 種類 | 割合 | 工数への影響 |
            |-|-|-|
            | AI(要レビュー) | 100% | 90% |
            | **割合×工数への影響の合計** | - | **90%減** |
          ||
        }
      }
      infra {
        label: "インフラ"
        class: ai-effective-weak

        cost-cut: {
          class: cost-cut
          description: ||md
            ## 作業項目
            - インフラ設計
              - IaC実装のために必要な情報をまとめる設計
              - 作図言語などで人間もAIも読むことができるインフラ構成図を作成する
              - StepFunctionなどは小規模のものはフローチャート化する

            ## AI導入による変化
            | | AsIs | ToBe | 割合 |
            |-|-|-|-|
            | インフラ構成設計 | 手作業 | AI(対話) | 100% |

            ## 定量的に削減できる工数
            | 種類 | 割合 | 工数への影響 |
            |-|-|-|
            | AI(対話) | 100% | 80% |
            | **割合×工数への影響の合計** | - | **80%減** |
          ||
        }
      }
    }

    model -> backend.endpoint
  }
  implementation: {
    direction: right
    label: "実装・単体テスト"

    cost-cut: {
      class: cost-cut
      label: 実装全体のコストへの影響
      description: ||md
        # 定量的に削減できる工数
        | 項目 | 割合 | 工数への影響 |
        |-|-|-|
        | フロントエンド - 画面 | 45% | 80% |
        | フロントエンド - APIクライアント | 5% | 90% |
        | バックエンド(サービス) - 認証/認可 | 5% | 70% |
        | バックエンド(サービス) - APIエンドポイント | 5% | 90% |
        | バックエンド(サービス) - サービス | 30% | 62% |
        | バックエンド(インフラ) - データベース | 5% | 82% |
        | バックエンド(インフラ) - IaC | 4% | 90% |
        | CI/CD - 構築 | 1% | 90% |
        | **割合×工数への影響の合計** | 100% | **75.0%減** |
        ### 注意点
        - 各実装項目はテスト(動作確認)までの工程を含む
      ||
    }

    frontend {
      label: "フロントエンド"
      view {
        label: "画面"
        class: ai-effective-weak
        cost-cut: {
          class: cost-cut
          description: ||md
            ## 実装対象
            - UIコンポーネント
            - 状態管理
            - ルーティング
            - UIテスト
            ## AI導入による変化
            | | AsIs | ToBe | 割合 |
            |-|-|-|-|
            | UIコンポーネント | 手作業 | AI(要レビュー) | 50% |
            | ルーティング | 手作業 | AI(一部手作業) | 20% | 
            | 状態管理 | 手作業 | AI(対話) | 20% |
            | UIテスト | 手作業 | AI(要レビュー) | 10% |

            ## 定量的に削減できる工数
            | 項目 | 割合 | 工数への影響 |
            |-|-|-|
            | AI(要レビュー) | 60% | 90%減 |
            | AI(対話) | 20% | 80%減 |
            | AI(一部手作業) | 20% | 50%減 |
            | **割合×工数への影響の合計** | - | **80%減** |
          ||
        }
      }

      api-client {
        label: "APIクライアント"
        class: ai-effective
        cost-cut: {
          class: cost-cut
          description: ||md
            ## AI導入による変化
            | | AsIs | ToBe | 割合 |
            |-|-|-|-|
            | クライアント(REST/GraphQL/WebSocket) | 手作業 | AI(要レビュー) | 50% |
            | エラー処理 | 手作業 | AI(要レビュー) | 30% |
            | リトライ処理 | 手作業 | AI(要レビュー) | 10% | 
            | モニタリング処理 | 手作業 | AI(要レビュー) | 10% |
            ## 定量的に削減できる工数
            | 種類 | 割合 | 工数への影響 |
            |-|-|-|
            | AI(要レビュー) | 100% | 90% |
            | **割合×工数への影響の合計** | - | **90%減** |
          ||
        }
      }
    }

    backend {
      label: "バックエンド"

      services {
        label: "サービス層"
        
        auth {
          label: "認証/認可"
          class: ai-effective-weak
          cost-cut: {
            class: cost-cut
            description: ||md
              ## AI導入による変化
              | | AsIs | ToBe | 割合 |
              |-|-|-|-|
              | ユーザ管理 | 手作業 | AI(要レビュー) | 25% |
              | 権限管理 | 手作業 | AI(要レビュー) | 25% |
              | セッション管理 | 手作業 | AI(一部手作業) | 25% |
              | OAuth実装 | 手作業 | AI(一部手作業) | 25% |
              ## 定量的に削減できる範囲
              | 項目 | 割合 | 工数への影響 |
              |-|-|-|
              | AI(要レビュー) | 50% | 90%減 |
              | AI(一部手作業) | 50% | 50%減 |
              | **割合×工数への影響の合計** | - | **70%減** |
            ||
          }
        }
        api {
          label: "APIエンドポイント"
          class: ai-effective
          cost-cut: {
            class: cost-cut
            description: ||md
              ## 実装項目
              - DTO実装
              - エンドポイント(REST/GraphQL/WebSocket)
              - 入力バリデーション(Request/Response)
              - ロギング
              - ヘルスチェック
              ## AI導入による変化
              | | AsIs | ToBe | 割合 |
              |-|-|-|-|
              | 実装作業 | 手作業 | AI(要レビュー) | 100% |
              ## 定量的に削減できる範囲
              | 項目 | 割合 | 工数への影響 |
              |-|-|-|
              | AI(要レビュー) | 100% | 90%減 |
              | **割合×工数への影響の合計** | - | **90%減** |
            ||
          }
        }
        service-definition {
          label: "サービス"
          class: ai-effective-weak
          cost-cut: {
            class: cost-cut
            description: ||md
              ## AI導入による変化
              | | AsIs | ToBe | 割合 |
              |-|-|-|-|
              | ドメインモデル(ビジネスルール、計算ロジック) | 手作業 | AI(一部手作業) | 60% |
              | 基盤クラス作成 | 手作業 | AI(一部手作業) | 10% |
              | CRUD処理 | 手作業 | AI(要レビュー) | 20% |
              | ユニットテスト | 手作業 | AI(要レビュー) | 10% |
              ## 定量的に削減できる範囲
              | 項目 | 割合 | 工数への影響 |
              |-|-|-|
              | AI(要レビュー) | 30% | 90%減 |
              | AI(一部手作業) | 70% | 50%減 |
              | **割合×工数への影響の合計** | - | **62%減** |
            ||
          }
        }
      }
      infrastructure {
        label: "インフラ層"

        # 永続化グループ（DBアクセス関連）
        db: {
          class: ai-effective
          label: "データベース"

          cost-cut: {
            class: cost-cut
            description: ||md
              ## AI導入による変化
              | | AsIs | ToBe | 割合 |
              |-|-|-|-|
              | ORMモデル定義(スキーマ記述、インデックス管理、カスケード削除設定) | 手作業 | AI(要レビュー) | 80% |
              | - DBマイグレーション | ORMからコマンド生成 | ORMからコマンド生成 | - |
              | - SQLクエリ | ORMからコマンド生成 | ORMからコマンド生成 | - |
              | トランザクション管理 | 手作業 | AI(一部手作業) | 20% |
              ## 定量的に削減できる範囲
              | 項目 | 割合 | 工数への影響 |
              |-|-|-|
              | AI(要レビュー) | 80% | 90%減 |
              | AI(一部手作業) | 20% | 50%減 |
              | **割合×工数への影響の合計** | - | **82%減** |
            ||
          }
        }
        iac: {
          label: "IaC(Infrastructure as Code)"
          class: ai-effective
          cost-cut: {
            class: cost-cut
            description: ||md
              ## 実装項目
              - 本番環境デプロイ
              - クラウドプロバイダ
              - コンテナオーケストレーション
              - サーバー管理
              - スケーリング
              - DB管理
              - バックアップ/リストア
              - ファイルストレージ
              ## AI導入による変化
              | | AsIs | ToBe | 割合 |
              |-|-|-|-|
              | 実装項目 | 手作業 | AI(要レビュー) | 100% |
              ## 定量的に削減できる範囲
              | 項目 | 割合 | 工数への影響 |
              |-|-|-|
              | AI(要レビュー) | 100% | 90%減 |
              | **割合×工数への影響の合計** | - | **90%減** |
            ||
          }
        }
      }

    }

    ci-cd: {
      label: "CI/CD"
      setup: {
        label: "構築"
        class: ai-effective
        cost-cut: {
          class: cost-cut
          description: ||md
          ## 定量的に削減できる範囲
          | 項目 | 割合 | 工数への影響 |
          |-|-|-|
          | 構築 | 100% | 90%減 |
          | **割合×工数への影響の合計** | - | **90%減** |
          ||
        }
      }
    }
    frontend -> ci-cd;
    backend -> ci-cd
  }
  design.frontend -> implementation.frontend.view
  design.backend -> implementation.frontend.api-client
  design.backend -> implementation.backend

  integration-test: {
    label: "結合テスト"
    direction: right
    "ユーザーフローのE2Eテスト"
    "API連携のE2Eテスト"
    "クロスブラウザテスト"

    black-box: "ブラックボックステスト"
    scenario: "シナリオテスト"
    contract: "契約テスト"
    staging: "ステージング環境テスト"

    security-review {
      label: "セキュリティレビュー"
    }
  }
  ops {
    direction: right
    label: "運用/保守"
    
    monitoring {
      label: "監視"
    }
    
    logging {
      label: "ログ管理"
    }
    
    incident {
      label: "障害対応"
    }
    
    backup {
      label: "バックアップ"
    }
    
    security {
      label: "セキュリティ運用"
    }
    
    scaling {
      label: "スケーリング"
    }
    
    maintenance {
      label: "メンテナンス"
    }
    
    feedback {
      label: "ユーザー統計 & フィードバック"
    }
  }

}
