classes {
  blank: {
    label: ""
    style: {
      fill: white
      stroke-width: 0
    }
  }
  dash: {
    label: ""
    style: {
      fill: white
      stroke-dash: 2
      stroke-width: 2
    }
  }
  task: {
    icon: "./list-check-solid-full.svg"
    icon.near: top-right
    style: {
      fill: white
    }
    grid-rows: 2
    grid-gap: 8
  }
  sdd: {
    icon: "./claudecode-color.svg"
    icon.near: top-left
    style: {
      fill: "#ddffdd"
    }
  }
}

grid-columns: 2

grid {
  grid-rows: 3
  class: blank

  pm: {
    label: ""
    description: ||md
      ## プロジェクト管理者
      - プロジェクト管理の方法は変化しません。
      - 従来通りBacklog等のタスクのWBSの状況がそのままの進捗状況となります。
    ||
  }

  legend: {
    label: "凡例"
    style {
      fill: white
    }
    task: {
      class: task
      label: ""
      description: ||md
        ## タスク
      ||
      sdd: {
        class: sdd
        label: "spec駆動開発で変化する範囲"
      }
    }
  }
}

develop {
  class: blank

  start: {
    label: "開発開始"
    shape: circle
  }

  start -> parent-tasks

  requirements {
    label: "要件一覧・仕様一覧"
    agreement {
      class: dash
      label: "お客様と合意済みのもの"
      excel {
        class: blank
        label: "データ構造資料"
        icon: "https://res-1.cdn.office.net/files/fabric-cdn-prod_20251008.001/assets/brand-icons/product/svg/excel_48x1.svg"
      }
      power-point {
        class: blank
        label: "ラフスケッチ"
        icon: "https://res-1.cdn.office.net/files/fabric-cdn-prod_20251008.001/assets/brand-icons/product/svg/powerpoint_48x1.svg"
      }
      design {
        class: blank
        label: "機能一覧"
        icon: "https://res-1.cdn.office.net/files/fabric-cdn-prod_20251008.001/assets/brand-icons/product/svg/excel_48x1.svg"
      }
    }
    requirement: {
      grid-columns: 3
      label: "内部文書"
      backlog: {
        label: ""
        shape: image
        icon: "https://backlog.com/app/themes/backlog-child/assets/img/common/logo/logo_backlog.svg"
      }
      markdown: {
        label: ""
        shape: image
        icon: "./markdown-brands-solid-full.svg"
      }
      environment: ||md
      ## エンジニアが事前考慮した情報群
      - 開発環境
        - フレームワーク
        - 言語
      - 運用環境
        - インフラ
        - セキュリティ
      ||
      api {
        class: blank
        label: "API・認証認可資料"
        icon: "https://res-1.cdn.office.net/files/fabric-cdn-prod_20251008.001/assets/brand-icons/product/svg/excel_48x1.svg"
      }
    }
  }

  ai-process {
      icon: "./claudecode-color.svg"
      label: "AIによる分析\n(Claude Code)"
  }
  requirements.agreement.excel -> ai-process: MarkItDownによる変換
  requirements.agreement.power-point -> ai-process: MarkItDownによる変換
  requirements.agreement.design -> ai-process: MarkItDownによる変換
  requirements.requirement -> ai-process: 必要に応じて\nMarkItDownによる変換

  ai-process -> parent-tasks.task
  parent-tasks {
    label: "親タスク群"
    icon: "https://backlog.com/app/themes/backlog-child/assets/img/common/logo/logo_backlog.svg"
    icon.near: top-left
    tooltip: ||md
      ## タスクの区切り方と消化の仕方
      - 1つの画面・機能≒1つの親タスクとします
      - 子タスクはAIに起票させ、エンジニアが内容を精査して修正を加えます
      - **「できる限り」モデルファーストでタスクを消化します**
      - AIはタスクに記載された情報を最も信頼性の高いソースとして処理します
      - 機能の規模によっては、タスクをまとめるor分割することはOK
      - AI自動生成が困難なものは、AIアシストによって実施するタスクを作る
    ||
    tooltip.near: center-left

    setup: {
      label: ""
      class: task
      grid-rows: 2
      grid-gap: 8
      description: ||md
        ## 開発環境の立ち上げ
        案件に合わせた開発環境を構築します。
      ||
      setup-sdd {
        label: ""
        class: sdd
        description: ||md
          ## spec駆動開発環境
          - spec駆動開発ファイル群を組み込みます。
            - skills/agents/mcpなどの設定します。
          - CLAUDE.mdをプロジェクトに合わせて書き換えます。
        ||
      }
    }

    task: {
      label: "親タスク(画面・機能)\nエピック or フィーチャー"
      class: task
      style.multiple: true
    }
  }

  requirements.requirement -> parent-tasks.setup

  design: {
    class: dash
    ux: {
      label: ""
      class: task
      description: ||md
        ## UX設計
        ### 入力
        - 画面
        - 機能
        ### エンジニアによる処理
        - AIが作るべきものの仕様書を記述
        - 画面遷移
      ||
      sdd: {
        label: ""
        class: sdd
        description: ||md
          ### 処理
          - プロトタイプ作成
          - ドメインモデルとの整合検査
          - 画面・機能の責務を精査
          - データモデル検査
          ### 出力
          - UX設計図
          - 画面が扱う情報のまとめ
        ||
      }
    }

    data-model: {
      class: task
      label: ""
      description: ||md
        ## データモデルの設計・実装
        > **エンジニアとAIが対話してデータ構造を決定する** タスクです。<br />
        > 関連する画面・機能に対するデータモデルを設計します。<br />
        > 以降の工程をAI自動化するために必要な手順です。

        ### 入力
        - データの名称(例えばCustomer、Employee)
          - フィールドの詳細
            - 上限値・下限値
            - 最大長
            - NULL許容などを定める
          - 論理削除型 or 物理削除型
          - リレーションとカスケード削除
      ||
      output {
        class: sdd
        label: ""
        description: ||md
          ### 処理
          - AIによるスキーマ設計
          ### 出力
          - 仕様(且つ実装)として保存
            - DBのスキーマを決定(schema.prismaなど)
            - DTOとバリデーションの決定<br />(Zod、schema.graphqlなど)
        ||
      }  
    }
  }
  design.ux -> frontend.design
  parent-tasks.task -> design.ux: "画面・機能"
  parent-tasks.task -> design.data-model: "画面・機能"

  design.data-model -> api: "DTO、DBスキーマ"
  design.data-model -> frontend.design: "DTO"
  api -> frontend.design: "API"

  api: {
    class: task
    label: ""
    description: ||md
      ## API設計・実装
      APIの実装と同期したほうが良いものを一括処理する
      ### 入力
      - DTO
      - スキーマ
    ||
    sdd: {
      label: ""
      class: sdd
      description: ||md
        ### 処理
        - API設計
        - テスト設計
        ### 出力
        - リゾルバーの実装
        - サービスの実装
        - ユニットテストコード
        - **DBマイグレーション**
      ||
    }
  }

  frontend {
    class: dash
    design: {
      class: task
      label: ""
      description: ||md
        ## フロントエンド設計
        ### 入力
        - DTO
        - API
      ||
      sdd: {
        label: ""
        class: sdd
        description: ||md
          ### 処理
          - サーバー側処理設計
          - 画面側表示・処理設計
          - 画面から呼び出すAPI
          ### 出力
          - 画面実装設計
        ||
      }
    }
    component: {
      class: task
      label: ""
      description: ||md
        ## コンポーネント設計・実装
        ### 入力
        - DTO(一部)
        - 機能
      ||
      sdd: {
        label: ""
        class: sdd
        description: ||md
          ### 処理
          - パラメーター設計
          - 機能設計
          - 実装
          ### 出力
          - 実装済みコンポーネント
        ||
      }
    }
    design -> component: "DTO(一部)、機能(一部)"
    design -> implementation: "DTO、API"
    component -> implementation: "コンポーネント"
    implementation: {
      class: task
      label: ""
      description: ||md
        ## フロントエンド実装
        ### 入力
        - 
      ||
      sdd: {
        label: ""
        class: sdd
        description: ||md
          ### 処理
          - 
          ### 出力
          - 画面実装結果
        ||
      }
    }
  }
}

